<?php
return [
    'adminEmail' => 'admin@example.com',
    'bossSignCheckSwitch' => 1,//sign校验 0为关闭校验 1开启校验
    'secretKey' => '7g2cf84185d032de45f95q2198a57',
    'jwt-secret' =>'jwt-e8773605ba20edbd6376',

    'permissionWhiteList' => [ //权限白名单
        'video/video-external/get-auth',
        'video/video-external/get-access-token',
        'video/video-external/refresh-token',
        'video/video-external/refresh-access-token',
        'user/users/login',
        'accident/accident/callback-notice',//阿里云测试队列
        'mdkweb/mdk-list/homepage-by',//mdk官网首页轮播图
        'mdkweb/mdk-list/recruit-list', //mdk官网首页招聘信息
        'user/user/index',//腾讯
        'accident/accident-st/accidentinfo',//事故检测 redis 队列数据
        'video/video-external/test'
    ],

    'signCheckWhite'=>[ //签名验证白名单
        'user/users/captcha',//验证码
        'data/ad-video/user-cost-new-export',//视频消耗
        'video/video-external/get-auth',
        'video/video-external/get-access-token',
        'video/video-external/refresh-token',
        'video/video-external/refresh-access-token',
        'external/interface/update-token',
        'external/interface/get-token',
        'basic/upload/upload',
        'accident/accident/callback-notice',//阿里云测试队列
        'mdkweb/mdk-list/homepage-by',//mdk官网首页轮播图
        'mdkweb/mdk-list/recruit-list', //mdk官网首页招聘信息
        'data/times-link/link',//时报链接
        'data/times-link/zyb',//时报链接
        'data/times-link/xh',//小猴时报链接
        'data/times-link/xhtwo',//小猴时报链接
        'data/times-link/xhthree',//小猴时报链接
        'data/times-link/xhfour',
        'data/times-link/xhss',//小猴搜索时报链接
        'data/data-report/account-export',//导出广告主账户
        'data/times-link/zybss',//作业帮搜索时报链接
        'data/times-link/gtss',//高途搜索时报链接
        'data/times-link/ggl',//瓜瓜龙时报链接
        'data/times-link/xm',//小马时报链接
        'data/times-link/jyxt',//金囿课堂时报链接
        'data/times-link/jyxty',//金囿课堂昨日日报链接
        'data/times-link/yfd',//猿辅导周报链接
        'data/times-link/yfdsca',//猿辅导
        'data/times-link/yfdscb',//猿辅导
        'data/times-link/yfdscc',//猿辅导
        'data/times-link/yfdscd',//猿辅导
        'data/times-link/yfdsce',//猿辅导
        'data/times-link/yfdscf',//猿辅导
        'data/times-link/yfdscg',//猿辅导
        'data/times-link/yfdsch',//猿辅导
        'data/times-link/yfdsci',//猿辅导
        'data/times-link/yfdscj',//猿辅导
        'data/times-link/zybzbk',//作业帮-直播课APP
        'data/times-link/sws',//金囿学堂-税务师
        'data/times-link/msb',//美术宝-小熊美术
        'data/times-link/sndd',//少年得到
        'data/pic-link/zybss',//作业帮-春季班搜索
        'data/times-link/yy',//鸭鸭
        'data/times-link/sdb',//水滴保
        'data/pic-link/xdfzx',//新东方在线
        'data/pic-link/xdfzxzlf',
        'data/pic-link/bbszxxl',//作业帮-帮帮识字
        'data/pic-link/jyxtch',//初会
        'data/pic-link/jyxtsws',//税务师
        'data/pic-link/jyxtzk',//中会
        'data/pic-link/msb',//美术宝
        'data/pic-link/zybskcjb',//作业帮-29元双科
        'data/pic-link/zybskcjbdy',
        'data/pic-link/wmsxyqndy',//微淼商学院-屈宁抖音
        'data/pic-link/wmsxyqntt',
        'data/pic-link/wmsxyqncsj',
        'data/pic-link/wmsxyjw',
        'data/pic-link/wmsxyzl',
        'data/pic-link/wmsxywm',
        'data/pic-link/xescx',//学而思网校春下
        'data/pic-link/xescs',
        'data/pic-link/hhswsxk',//火花思维数学课
        'data/pic-link/hhswzbk',//火花思维直播课
        'data/pic-link/gtss',//高途搜索
        'data/pic-link/yfdaz',//猿辅导A组
        'data/pic-link/bmswdk',//斑马思维单科
        'data/pic-link/yyyw',//鸭鸭语文
        'data/pic-link/yyywss',//鸭鸭语文
        'data/pic-link/xesdy',
        'data/pic-link/xhyw',
        'data/pic-link/xhsy',
        'data/pic-link/xhsyf',
        'data/pic-link/xhsw',
        'data/pic-link/yfdapp',
        'data/pic-link/snddyd',
        'data/pic-link/xhswf',//小猴-思维非20
        'data/pic-link/wmsxyss',//微淼商学院-搜索
        'data/pic-link/xdfzxky',//新东方在线-考研
        'data/pic-link/xhss',//小猴-ai课
        'data/pic-link/bmyylb',//斑马英语联报
        'data/pic-link/ngkx',//南瓜科学
        'data/pic-link/gglyw',//瓜瓜龙语文
        'data/pic-link/hhswsxk19',//火花思维-数学19.9元
        'data/pic-link/qbwxsx',//清北网校-清北数学
        'data/pic-link/qkd',//趣课多
        'data/pic-link/ggl',//瓜瓜龙英语
        'data/pic-link/gglsw',//瓜瓜龙思维
        'data/pic-link/xhsw69',//小猴思维69元3科联报
        'data/pic-link/xhswsy',//小猴思维数语50元
        'data/pic-link/bcm',//编程猫
        'data/pic-link/gglms',//瓜瓜龙美术
        'data/pic-link/xhsw49',
        'data/pic-link/by',//伴鱼
        'data/pic-link/msbydy',//美术宝1对1
        'data/pic-link/msbxbk',//美术宝小班课
        'data/pic-link/jyxtchtl',//金囿学堂初会-童琳
        'data/pic-link/xhyy',//小猴英语
        'tool/batch-plan/upload-file',//上传文件
        'user/user/index',//腾讯
        'data/pic-link/msbxzk',//美术宝写字课
        'data/pic-link/md',//米堆
        'data/pic-link/zs',//职上
        'data/pic-link/jyxtgy',//金囿学堂-初会搜索
        'data/pic-link/gglyws',//瓜瓜龙语文
        'data/pic-link/gtzq',//高途钟琴
        'data/pic-link/yhbzhaqx',//账户安全险
        'data/pic-link/yhbzjx',//重疾险
        'data/pic-link/gtsam',//高途sam
        'data/pic-link/yhbzjxdy',//萤火保-重疾险-抖音
        'data/pic-link/zgpa',//中国平安
        'data/pic-link/zaxd',//众安小贷
        'data/pic-link/gtzx',//高途在线
        'data/pic-link/hnbx',//黑牛保险
        'data/pic-link/hnbxzjx',//黑牛保险-重疾险
        'data/pic-link/hnbxcsj',//黑牛保险
        'data/pic-link/hnbxylsq',//黑牛保险-养老社区
        'data/pic-link/yszz',//影视制作
        'data/times-link/ylx',//夜来香
        'data/times-link/mm',//陌陌
        'data/times-link/mmcgzh',//陌陌-常规召回
        'data/times-link/mmrta',//陌陌-RTA
        'data/pic-link/kkbgk',//开课吧-公考
        'data/pic-link/zaxds',//众安小贷
        'data/pic-link/kkbzk',//开课吧-自考
        'data/pic-link/msss',//开课吧-免试硕士
        'data/times-link/zabx',//众安保险-百万防癌医疗险
        'data/times-link/qyl',//有缘网-趣约聊
        'data/times-link/qq',//有缘网-亲亲
        'data/pic-link/ylx',//百万防癌医疗险
        'data/pic-link/ybzjx',//元保-重疾险
        'data/pic-link/zaxdapp',//众安小贷-app下载英晖组
        'data/pic-link/hjzb',//花椒直播
        'data/pic-link/zzlzx',//周周领赠险
        'data/pic-link/dpjy',//大鹏教育-国画
        'data/pic-link/soulios',
        'data/pic-link/soul',
        'data/pic-link/zs0yk',
        'data/pic-link/xn',//小牛
        'data/pic-link/nyss',//开课吧-农业硕士
        'accident/accident-st/accidentinfo'//事故检测 redis 队列数据
    ],

    'whiteList' => [ //token验证白名单
        'user/users/captcha',//验证码
        'data/ad-video/user-cost-new-export',//视频消耗
        'video/video-external/get-auth',
        'video/video-external/get-access-token',
        'video/video-external/refresh-token',
        'video/video-external/refresh-access-token',
        'user/users/login',//后台登录
        'user/users/token-login',//同步登陆
        'external/interface/update-token', //老后台同步token
        'external/interface/get-token',
        'user/user/index', //测试队列
        'accident/accident/callback-notice',//阿里云测试队列
        'mdkweb/mdk-list/homepage-by',//mdk官网首页轮播图
        'mdkweb/mdk-list/recruit-list', //mdk官网首页招聘信息
        'data/times-link/link',//时报链接
        'data/times-link/zyb',//时报链接
        'data/times-link/xh',//小猴时报链接
        'data/times-link/xhtwo',//小猴时报链接
        'data/times-link/xhthree',//小猴时报链接
        'data/times-link/xhfour',
        'data/times-link/xhss',//小猴搜索时报链接
        'data/data-report/account-export',//导出广告主账户
        'data/times-link/zybss',//作业帮搜索时报链接
        'data/times-link/gtss',//高途搜索时报链接
        'data/times-link/ggl',//瓜瓜龙时报链接
        'data/times-link/xm',//小马时报链接
        'data/times-link/jyxt',//金囿课堂时报链接
        'data/times-link/jyxty',//金囿课堂昨日日报链接
        'data/times-link/yfd',//猿辅导周报链接
        'data/times-link/yfdsca',//猿辅导
        'data/times-link/yfdscb',//猿辅导
        'data/times-link/yfdscc',//猿辅导
        'data/times-link/yfdscd',//猿辅导
        'data/times-link/yfdsce',//猿辅导
        'data/times-link/yfdscf',//猿辅导
        'data/times-link/yfdscg',//猿辅导
        'data/times-link/yfdsch',//猿辅导
        'data/times-link/yfdsci',//猿辅导
        'data/times-link/yfdscj',//猿辅导
        'data/times-link/zybzbk',//作业帮-直播课APP
        'data/times-link/sws',//金囿学堂-税务师
        'data/times-link/msb',//美术宝-小熊美术
        'data/times-link/sndd',//少年得到
        'data/times-link/yy',//鸭鸭
        'data/times-link/sdb',//水滴保
        'data/pic-link/zybss',//作业帮-春季班搜索
        'data/pic-link/xdfzx',//新东方在线
        'data/pic-link/xdfzxzlf',
        'data/pic-link/bbszxxl',//作业帮-帮帮识字
        'data/pic-link/jyxtch',//初会
        'data/pic-link/jyxtsws',//税务师
        'data/pic-link/jyxtzk',//中会
        'data/pic-link/msb',//美术宝
        'data/pic-link/zybskcjb',//作业帮-29元双科
        'data/pic-link/zybskcjbdy',
        'data/pic-link/wmsxyqndy',//微淼商学院-屈宁抖音
        'data/pic-link/wmsxyqntt',
        'data/pic-link/wmsxyqncsj',
        'data/pic-link/wmsxyjw',
        'data/pic-link/wmsxyzl',
        'data/pic-link/wmsxywm',
        'data/pic-link/xescx',//学而思网校春下
        'data/pic-link/xescs',
        'data/pic-link/hhswsxk',//火花思维数学课
        'data/pic-link/hhswzbk',//火花思维直播课
        'data/pic-link/gtss',//高途搜索
        'data/pic-link/yfdaz',//猿辅导A组
        'data/pic-link/bmswdk',//斑马思维单科
        'data/pic-link/yyyw',//鸭鸭语文
        'data/pic-link/yyywss',//鸭鸭语文
        'data/pic-link/xesdy',
        'data/pic-link/xhyw',
        'data/pic-link/xhsy',
        'data/pic-link/xhsyf',
        'data/pic-link/xhsw',
        'data/pic-link/yfdapp',
        'data/pic-link/snddyd',
        'data/pic-link/xhswf',//小猴-思维非20
        'data/pic-link/wmsxyss',//微淼商学院-搜索
        'data/pic-link/xdfzxky',//新东方在线-考研
        'data/pic-link/xhss',//小猴-ai课
        'data/pic-link/bmyylb',//斑马英语联报
        'data/pic-link/ngkx',//南瓜科学
        'data/pic-link/gglyw',//瓜瓜龙语文
        'data/pic-link/hhswsxk19',//火花思维-数学19.9元
        'data/pic-link/qbwxsx',//清北网校-清北数学
        'data/pic-link/qkd',//趣课多
        'data/pic-link/ggl',//瓜瓜龙英语
        'data/pic-link/gglsw',//瓜瓜龙思维
        'data/pic-link/xhsw69',//小猴思维69元3科联报
        'data/pic-link/xhswsy',//小猴思维数语50元
        'data/pic-link/bcm',//编程猫
        'data/pic-link/gglms',//瓜瓜龙美术
        'data/pic-link/xhsw49',
        'data/pic-link/by',//伴鱼
        'data/pic-link/msbydy',//美术宝1对1
        'data/pic-link/msbxbk',//美术宝小班课
        'data/pic-link/jyxtchtl',//金囿学堂初会-童琳
        'data/pic-link/xhyy',//小猴英语
        'user/user/index',//腾讯
        'data/pic-link/msbxzk',//美术宝写字课
        'data/pic-link/md',//米堆
        'data/pic-link/zs',//职上
        'data/pic-link/gglyws',//瓜瓜龙语文
        'data/pic-link/jyxtgy',//金囿学堂-初会搜索
        'data/pic-link/gtzq',//高途钟琴
        'data/pic-link/yhbzhaqx',//账户安全险
        'data/pic-link/yhbzjx',//重疾险
        'data/pic-link/gtsam',//高途sam
        'data/pic-link/yhbzjxdy',//萤火保-重疾险-抖音
        'data/pic-link/zgpa',//中国平安
        'data/pic-link/zaxd',//众安小贷
        'data/pic-link/gtzx',//高途在线
        'data/pic-link/hnbx',//黑牛保险
        'data/pic-link/hnbxzjx',//黑牛保险-重疾险
        'data/pic-link/hnbxcsj',//黑牛保险
        'data/pic-link/hnbxylsq',//黑牛保险-养老社区
        'data/pic-link/yszz',//影视制作
        'data/times-link/ylx',//夜来香
        'data/times-link/mm',//陌陌
        'data/times-link/mmcgzh',//陌陌-常规召回
        'data/times-link/mmrta',//陌陌-RTA
        'data/pic-link/kkbgk',//开课吧-公考
        'data/pic-link/zaxds',//众安小贷
        'data/pic-link/kkbzk',//开课吧-自考
        'data/pic-link/msss',//开课吧-免试硕士
        'data/times-link/zabx',//众安保险-百万防癌医疗险
        'data/times-link/qyl',//有缘网-趣约聊
        'data/times-link/qq',//有缘网-亲亲
        'data/pic-link/ylx',//百万防癌医疗险
        'data/pic-link/ybzjx',//元保-重疾险
        'data/pic-link/zaxdapp',//众安小贷-app下载英晖组
        'data/pic-link/hjzb',//花椒直播
        'data/pic-link/zzlzx',//周周领赠险
        'data/pic-link/dpjy',//大鹏教育-国画
        'data/pic-link/soulios',
        'data/pic-link/soul',
        'data/pic-link/zs0yk',
        'data/pic-link/xn',//小牛
        'data/pic-link/nyss',//开课吧-农业硕士
        'accident/accident-st/accidentinfo'//事故检测 redis 队列数据
    ],

    'fly_dev' => [ //机器人密钥 测试
        'appid'=>'cli_9f4e2410e13d500d',
        'appSecret'=>'hp19wSYxriYPlts6d4vVtfA7f2kNkRQA'
    ],
    'fly_test' => [ //机器人密钥 测试
        'appid'=>'cli_9f4e2410e13d500d',
        'appSecret'=>'hp19wSYxriYPlts6d4vVtfA7f2kNkRQA'
    ],
    'fly_prod' => [ //机器人密钥 正式
        'appid'=>'cli_9f18c17c51f7900e',
        'appSecret'=>'QOsFkLuMOwPQawaMDhN9LbTsbxs0yKit'
    ],
    
    'agent_type' => array('1641082415338508'),//搜索流代理商id
    'video_http'=>'https://cc.oceanengine.com/v/video_player',
    'video_url'=>"https://ad.oceanengine.com/pages/video-player-safe/index.html", //素材视频url
    'video_player'=>"//sf1-scmcdn-tos.pstatp.com/goofy/oe/platform_web/static/image/play.svg?f3db861d10cf31d0ff0778b1b4331ba9", //video_player
    'video_imgurl'=>"https://sf1-ttcdn-tos.pstatp.com/obj/",
    'material_url'=>"https://cc.oceanengine.com/st/share-video/",
    'image_mode'=>[
        'CREATIVE_IMAGE_MODE_SMALL'=>'小图',
        'CREATIVE_IMAGE_MODE_LARGE'=>'大图',
        'CREATIVE_IMAGE_MODE_GROUP'=>'组图',
        'CREATIVE_IMAGE_MODE_VIDEO'=>'横版视频',
        'CREATIVE_IMAGE_MODE_GIF'=>'GIF图',
        'CREATIVE_IMAGE_MODE_LARGE_VERTICAL'=>'大图竖图',
        'CREATIVE_IMAGE_MODE_VIDEO_VERTICAL'=>'竖版视频',
        'TOUTIAO_SEARCH_AD_IMAGE'=>'搜索大图',
        'SEARCH_AD_SMALL_IMAGE'=>'搜索小图',
        'CREATIVE_IMAGE_MODE_UNION_SPLASH'=>'穿山甲开屏图片',
        'CREATIVE_IMAGE_MODE_UNION_SPLASH_VIDEO'=>'穿山甲开屏视频',
        'CREATIVE_IMAGE_MODE_DISPLAY_WINDOW'=>'搜索橱窗',
        'MATERIAL_IMAGE_MODE_TITLE'=>'标题类型',
        'CREATIVE_IMAGE_MODE_AWEME_LIVE'=>'直播画面类型',
        'CREATIVE_IMAGE_MODE_PLAYABLE_HORIZONTAL'=>'横版试玩素材类型',
        'CREATIVE_IMAGE_MODE_PLAYABLE_VERTICAL'=>'竖版试玩素材类型'
    ],
    //过滤已转化用户类型
    'hide_if_converted'=>[
        'NO_EXCLUDE'=>'不过滤',
        'AD'=>'广告计划',
        'CAMPAIGN'=>'广告组',
        'ADVERTISER'=>'广告账户',
        'APP'=>'APP',
        'CUSTOMER'=>'公司账户',
    ],
    //过滤时间范围
    'converted_time_duration'=>[
        'TODAY'=>'当天',
        'SEVEN_DAY'=>'7天',
        'ONE_MONTH'=>'1个月',
        'THREE_MONTH'=>'3个月',
        'SIX_MONTH'=>'6个月',
        'TWELVE_MONTH'=>'12个月',
    ],
    //手机品牌
    'device_brand'=>[
        'HONOR'=>'荣耀',
        'APPLE'=>'苹果',
        'HUAWEI'=>'华为',
        'XIAOMI'=>'小米',
        'SAMSUNG'=>'三星',
        'OPPO'=>'OPPO',
        'VIVO'=>'VIVO',
        'MEIZU'=>'魅族',
        'GIONEE'=>'金立',
        'COOLPAD'=>'酷派',
        'LENOVO'=>'联想',
        'LETV'=>'乐视',
        'ZTE'=>'中兴',
        'CHINAMOBILE'=>'中国移动',
        'HTC'=>'HTC',
        'PEPPER'=>'小辣椒',
        'NUBIA'=>'努比亚',
        'HISENSE'=>'海信',
        'QIKU'=>'奇酷',
        'TCL'=>'TCL',
        'SONY'=>'索尼',
        'SMARTISAN'=>'锤子手机',
        '360'=>'360手机',
        'ONEPLUS'=>'一加手机',
        'LG'=>'LG',
        'MOTO'=>'摩托罗拉',
        'NOKIA'=>'诺基亚',
        'GOOGLE'=>'谷歌',
    ],
    //智能放量
    'auto_extend_targets'=>[
        'REGION'=>'地域',
        'GENDER'=>'性别',
        'AGE'=>'年龄',
        'AD_TAG'=>'兴趣分类',
        'INTEREST_TAG'=>'兴趣关键词',
        'CUSTOM_AUDIENCE'=>'自定人群-定向',
        'INTEREST_ACTION'=>'行为兴趣'
    ],
    'inventory'=>[
        'INVENTORY_FEED'=>'头条信息流',
        'INVENTORY_TEXT_LINK'=>'头条文章详情页',
        'INVENTORY_VIDEO_FEED'=>'西瓜信息流',
        'INVENTORY_HOTSOON_FEED'=>'火山信息流',
        'INVENTORY_AWEME_FEED'=>'抖音信息流',
        'INVENTORY_UNION_SLOT'=>'穿山甲',
        'UNION_BOUTIQUE_GAME'=>'ohayoo精品游戏',
        'INVENTORY_UNION_SPLASH_SLOT'=>'穿山甲开屏广告',
        'INVENTORY_AWEME_SEARCH'=>'搜索广告——抖音位',
        'INVENTORY_SEARCH'=>'搜索广告——头条位（广告投放）',
        'INVENTORY_UNIVERSAL'=>'通投智选（广告投放）',
        'INVENTORY_BEAUTY'=>'轻颜相机',
        'INVENTORY_PIPIXIA'=>'皮皮虾',
        'INVENTORY_AUTOMOBILE'=>'懂车帝',
        'INVENTORY_STUDY'=>'好好学习',
        'INVENTORY_FACE_U'=>'faceu',
        'INVENTORY_TOMATO_NOVEL'=>'番茄小说'
    ],
    'inventoryInt'=>[
        1=>'头条信息流',
        2=>'头条文章详情页',
        3=>'西瓜信息流',
        4=>'火山信息流',
        5=>'抖音信息流',
        6=>'穿山甲',
        7=>'ohayoo精品游戏',
        8=>'穿山甲开屏广告',
        9=>'搜索广告——抖音位',
        10=>'搜索广告——头条位',
        11=>'通投智选',
        12=>'番茄小说',
        13=>'轻颜相机',
        14=>'皮皮虾',
        15=>'懂车帝',
        16=>'好好学习',
        17=>'faceu',
    ],
    'age'=>[
        "AGE_BETWEEN_18_23"=>"18-23岁",
        "AGE_BETWEEN_24_30"=>"24-30岁",
        "AGE_BETWEEN_31_40"=>"31-40岁",
        "AGE_BETWEEN_41_49"=>"41-49岁",
        "AGE_ABOVE_50"=>"大于等于50岁",
    ],
    'gender'=>[
        "1"=>"不限",
        "2"=>"男",
        "3"=>"女"
    ],
    'en_gender'=>[
        "NONE" => 1,
        "GENDER_MALE" => 2,
        "GENDER_FEMALE" => 3
    ],
    'district'=>[
        "NONE"=>"不限",
        "CITY"=>"省市"
    ],
    'optStatus'=>[
        "AD_CONVERT_OPT_STATUS_ENABLE"=>"启用",
        "AD_CONVERT_OPT_STATUS_DISABLE"=>"删除"
    ],
    "status"=>[
        "AD_CONVERT_STATUS_ACTIVE"=>"活跃（激活）",
        "AD_CONVERT_STATUS_INACTIVE"=>"不活跃（未激活）"
    ],
    "convertSourceType"=>[
        "AD_CONVERT_SOURCE_TYPE_INTERNAL"=>"平台提供的转化工具",
        "AD_CONVERT_SOURCE_TYPE_JS"=>"代码检测转化",
        "AD_CONVERT_SOURCE_TYPE_XPATH"=>"路径转化",
        "AD_CONVERT_SOURCE_TYPE_APP_DOWNLOAD"=>"应用下载API",
        "AD_CONVERT_SOURCE_TYPE_API"=>"落地页API（废弃，不能新建，历史数据保留)",
        "AD_CONVERT_SOURCE_TYPE_H5_API"=>"落地页API（H5）",
        "AD_CONVERT_SOURCE_TYPE_SDK"=>"应用下载SDK",
        "AD_CONVERT_SOURCE_TYPE_OPEN_URL"=>"应用直达API（应用直达链接）",
        "AD_CONVERT_SOURCE_TYPE_NORMAL_APP_DOWNLOAD"=>"普通应用下载",
        "AD_CONVERT_SOURCE_TYPE_CONFIG"=>"无转化跟踪",
        "AD_CONVERT_SOURCE_TYPE_CPS_GAME"=>"内部游戏cps应用下载",
        "AD_CONVERT_SOURCE_TYPE_APP_API_TEMAI"=>"落地页API(支持特卖)"
    ],
    'source'=>[
        "CUSTOM_AUDIENCE_TYPE_UPLOAD"=>"上传",
        "CUSTOM_AUDIENCE_TYPE_EXTEND"=>"扩展",
        "CUSTOM_AUDIENCE_TYPE_OPERATE"=>"运算",
        "CUSTOM_AUDIENCE_TYPE_RULE"=>"规则",
        "CUSTOM_AUDIENCE_TYPE_DATA_SOURCE"=>"文件数据源上传",
        "CUSTOM_AUDIENCE_TYPE_THIRD_PARTY"=>"第三方数据规则",
        "CUSTOM_AUDIENCE_TYPE_BRAND"=>"品牌DMP规则包",
        "CUSTOM_AUDIENCE_TYPE_FRIEND"=>"好友扩展",
        "CUSTOM_AUDIENCE_TYPE_THEME"=>"运营主题",
        "CUSTOM_AUDIENCE_TYPE_FINANCE"=>"金融数据",
        "CUSTOM_AUDIENCE_TYPE_PACK_RULE"=>"pack_rule运算",
        "CUSTOM_AUDIENCE_TYPE_ONE_KEY"=>"一键拓展",
        "CUSTOM_AUDIENCE_TYPE_DOU_PLUS"=>"抖+粉丝合并包"
    ],
    "progress"=>[
        -3=>"加拍被驳回",
        -2=>"待主管审核",
        -1=>"视频被驳回",
        0=>"视频待推送",
        1=>"订单待分配",
        2=>"脚本待上传",
        3=>"视频待上传",
        4=>"订单已终止",
        9=>"订单已完成"
    ],
    "shot_class"=>[
        1=>"正常拍摄",
        2=>"加拍",
        3=>"混剪"
    ],
    "video_class"=>[
        0=>"未设置",
        1=>"口播",
        2=>"情景剧",
        3=>"vlog",
        4=>"其他"
    ],

    "group"=>[
        //超管
        1=>[
            1=>[
                133=>'一部',
                135=>'二部',
                373=>'合肥',
             //   0=>'其他',
            ]
        ],
        //总经理
        129=>[
            3=>[
                133=>'一部',
                135=>'二部',
                373=>'合肥',
            //    0=>'其他',
            ]
        ],
        //副总经理
        131=>[
            //徐学梅
            11=>[
                133=>'一部',
                135=>'二部',
                373=>'合肥',
//                0=>'其他',
            ],
            //祁俊
            655=>[
                133=>'一部',
                135=>'二部',
                373=>'合肥',
//                0=>'其他',
            ],
        ],
        //1部负责人
        793=>[
            //高畅
            5=>[
                133=>'一部',
                135=>'二部',
                373=>'合肥',
            ]
        ],
        //质检组主管
        747=>[
            //张海鹏
            287=>[
                267=>'team1',
                405=>'team2',
                407=>'team3',
            ],
        ],
        //1部运营总监
        171=>[
            //马英辉team1
            65=>[
                151=>'一组',
                155=>'二组',
                157=>'三组',
                159=>'四组',
                0=>'m',

            ],
            //崔行明team2
            309=>[
                409=>'一组',
                411=>'二组',
                413=>'三组',
                0=>'m', //跑自己账户数据

            ],
        ],
        //1部运营经理
        795=>[
            //陈琦team3
            297=>[
                415=>'一组',
//                0=>'m',
            ]
        ],
        //1部主管
        173=>[
            //董咪咪
            83=>[151=>'一组'],
            165=>[155=>'二组'],
            293=>[155=>'二组'],
            157=>[157=>'三组'],
            189=>[409=>'一组'],
            317=>[409=>'一组'],
            191=>[411=>'二组'],
            717=>[411=>'二组'],
            143=>[413=>'三组'],
        ],

        //2部负责人
        799=>[
            //孙雪
            371=>[
                133=>'一部',
                135=>'二部',
                373=>'合肥',
            ]
        ],
        //二部运营经理
        801=>[
            //team1孙英洲
            13=>[
                287=>'一组',
            ],
            //team2郭建广
            49=>[
                287=>'一组',
            ],
            //team3 范佳
            375=>[
                295=>'一组',
                427=>'二组',
                0=>'m',
            ],
            //team4陈思思
            219=>[
                293=>'一组',
                0=>'m',
            ],
        ],
        //2部主管
        191=>[
            //Team3-1组 王娅南
            389=>[295=>'一组'],
            //Team3-2组 吕雪艳
            437=>[427=>'二组'],
        ],

        //合肥分公司总监
        775=>[
            //潘光宇
            507=>[
                133=>'一部',
                135=>'二部',
                373=>'合肥',
            ],
        ],

    ],
    //查看所有人权限角色id
    "ManagerRole"=>[1,129,131],

    //--------------------------------------------------
    //超管 总经理 副总经理
    "adminManager"=>[1,129,131,847],
    //部门负责人
    "departManagerHead"=>[793,799,775],
    //质检主管
    "testManager"=>[747],
    //小组主管角色
    "groupManager"=>[191,173],
    //总监角色
    "departManager"=>[171,795,801],
    //经理id 子品牌筛选需特殊处理
    "managerId"=>[13,49,219,297],
    //销售总监及助理角色
    "sellerManager"=>[131,135,725],
    //销售人员
    "sellerPersonnel"=>[137],
    //运营支持部
    "yyDepartment"=>[147],
    //优化师角色
    "optimizerName"=>[177,193,203,757,727,737,761],
    //总经理 只查一部 二部 合肥公司数据
    "adminGroup"=>[133,135,373],
    //经理、总监、负责人、总经理、管理员角色id
    "managerRoleID" =>[1,129,131,793,799,775,171,795,801],
    //商务部门角色
    "commerceRoleID"=>[133,135,137],
    //演员列表视频消耗角色
    "actorRoleID"=>[149,129,131,793,799,775,171,795,1],
    //质检系统需要权限的角色  优化师 运营主管 负责人
    "checkRoleID"=>[177,173,171,793,801],
    //财务经理 财务助理
    "cwRoleID" =>[213,219],
    //设计总监 设计经理
    "designID" =>[205,207],
    //设计部门所有角色 设计总监、设计经理、平面设计
    "designsID" =>[205,207,211],
    "demandType" => ['1'=>'数据报表','2'=> '素材类','3'=> '视频流程','4'=> '计划搭建','5'=> '事故监测','6'=> '内部培训','7'=> '资金管理','8'=> '其他'],

];
